### ISSUE TITLE
Problem with output CSS

### ISSUE THREAD

**Issue by ravishakya** [presscodes/kirki#2425]
The output is not working with slider and typography and with many more controls.

**Comment by ravishakya** [comment]
It works on the customizer previewer but not on the frontend.

**Comment by contactjavas** [comment]
Hi @ravishakya , could you please provide code or website link that can help us to check it?
The more information you provide, the easier/ faster we get to it.

Thanks for your understanding.
Looking forward to your reply.

**Comment by contactjavas** [comment]
Hi @ravishakya  , could you please try this version (v4.0.4)?
[kirki.zip](https://github.com/kirki-framework/kirki/files/7796248/kirki.zip)

This is not available yet in WordPress plugins repository, so you'd need to update yours manually.
Please let us know if this fixes your issue.

Thanks!

**Comment by contactjavas** [comment]
Hi @ravishakya , we've created another build (`v4.0.5`). Would you mind to test it against CSS output issue?
Here is the download link: [v4.0.5](https://github.com/kirki-framework/kirki/files/7801143/kirki.zip)

Thanks!

**Comment by ravishakya** [comment]
Hi,

Just tested the new version but it is still not working. This is my theme https://wordpress.org/themes/bizberg/

You might want to comment those lines in functions.php. We have included the plugin and extend the kirki with our own addons for kirki.

![image](https://user-images.githubusercontent.com/11089018/147919071-7e7f3c6d-5a87-472c-9273-1cfae36f6490.png)

Thank You

**Comment by mapsteps** [comment]
> The output is not working with slider and typography and with many more controls.

Hi @ravishakya,

Can you share what controls exactly don't output CSS for you? This will make it much easier for us to test. Please share the code of the controls in question with us. It don't need to be all of them but a variety of controls that don't output the CSS would be great so we can recreate this on our end & run some more in-depth tests.

Thank you.

**Comment by mapsteps** [comment]
I have now tried to test this but after removing the "plugins" as shown in the screenshot, I was getting tons of warning across the board. We would need a clean baseline to test this better. There is a high chance here that something is breaking before our CSS output can actually do its job.

We have just tested the CSS output with a bunch of controls on a different theme and things were working fine for us. Still, a lot of people have reported similar issues with v4 so we will continue to look into this. We hope to get to the root of this problem soon.

**Comment by sebastianthulin** [comment]
Hi! I have this issue aswell but haven't had the time to investigate deeply. Concluded that filters dosen't run. If they haven't been removed, it may give you some insights about the issue. 

Example filter: add_filter('kirki_' . \Municipio\Customizer::KIRKI_CONFIG . '_styles', array($this, 'filterPageWidth'));

Our theme is opensource and can be downloaded from: https://github.com/helsingborg-stad/Municipio/tree/3.0/develop. Enable Kirki 4 as a plugin to reproduce the errors stated in this issue. 

This issue is affecting all fields for us.

**Comment by contactjavas** [comment]
Hi @sebastianthulin @ravishakya , would you mind to test the 4.0.8 version? Link: [v4.0.8](https://github.com/kirki-framework/kirki/files/7814887/kirki.zip)

Thanks!

**Comment by contactjavas** [comment]
> Hi! I have this issue aswell but haven't had the time to investigate deeply. Concluded that filters dosen't run. If they haven't been removed, it may give you some insights about the issue.
> 
> Example filter: add_filter('kirki_' . \Municipio\Customizer::KIRKI_CONFIG . '_styles', array($this, 'filterPageWidth'));
> 
> Our theme is opensource and can be downloaded from: https://github.com/helsingborg-stad/Municipio/tree/3.0/develop. Enable Kirki 4 as a plugin to reproduce the errors stated in this issue.
> 
> This issue is affecting all fields for us.

@sebastianthulin , thank you for the link.
We'll test it

**Comment by sebastianthulin** [comment]
Thank you for the link! I have tested with version 4.0.8 without any change.

**Comment by mapsteps** [comment]
@sebastianthulin, @ravishakya, can you please test the latest version below to see if that makes any difference?

Thanks!

[kirki-4-0-9.zip](https://github.com/kirki-framework/kirki/files/7825264/kirki-4-0-9.zip)

**Comment by ravishakya** [comment]
Hi,

It did work partially, when control has active_callback the output is not working. Everything is working on the customizer previewer but on the frontend, it is not working.

**Comment by sebastianthulin** [comment]
Grate job! 4.0.9 works really well for me, even with active_callback. Im only using === operator with boolean values in this helper. Maybe @ravishakya is having another approach. 

Here are my Helper function: https://github.com/helsingborg-stad/Municipio/blob/3.0/develop/library/Helper/KirkiCondidional.php

**Comment by ravishakya** [comment]
The problem I am having is I have a parent and child theme. I have one controller in the parent theme and from the child theme, I am changing the default value using filters. Now the problem is in the child theme the filters are not working to change the default values. before Kirki 4 it is working.

My parent theme seems to be working fine with the latest Kirki version. But I am changing the values from the child theme and plugin. That is not working.

**Comment by contactjavas** [comment]
Glad that fixes the issue @sebastianthulin ! 

@ravishakya , which filter do you use? I'll try [your theme](https://wordpress.org/themes/bizberg/)
Would it be possible if you provide us the child theme?

Thank you guys, for helping us testing it :)

**Comment by ravishakya** [comment]
I will provide you with the theme. Give me some hrs currently I am going home so will take some hrs.

Thank You

**Comment by ravishakya** [comment]
Here is the download link of child theme and parent theme

https://drive.google.com/file/d/19KxCRK-zRqdyS60B9kfG0SDuvaeaz9Zr/view?usp=sharing
https://drive.google.com/file/d/1I5JdJUEdKKDbwMrUOZ7Sd-3Ufb50G8iS/view?usp=sharing

if you check the customizer preview and frontend the fonts are not loading on the frontend.

**Comment by contactjavas** [comment]
Thank you @ravishakya for providing the themes & the info.

### The main bug

The problem is on the checkbox field which is the parent of the `active_callback` fields below it.
The expected value in this case is `true` .

The checkbox element it self is checked and has correct value (`true`)
But if we save it without interacting with the checkbox it self (without toggling the checkbox _off_ -> then _on_ again), the saved value is `false` .  But once we interact with the checkbox (by toggling it _off_ -> then _on_ again), then the saved value is correct (`true`)

We're working on this. We'll let you know after this is fixed.

---

Also, I noticed there are other bugs in `bizberg` theme:
- kirki-simple-color
  - file: wp-content/themes/bizberg/inc/plugins/kirki-simple-color/index.php
  - problem: Kirki 4 doesn't use `wp-color-picker` for the main color picker anymore. And this _kirki-simple-color_ is a custom control. So that the fix seems better to be implemented in `bizberg` instead of Kirki.
- kirki-advanced-repeater
  - file: wp-content/themes/bizberg/inc/plugins/kirki-advanced-repeater/index.php
  - problem: Kirki 4 doesn't use `select2` anymore for it's control-select. It uses `react-select`. And this _kirki-advanced-repeater_ is also a custom control. So that the fix seems better to be implemented in `bizberg` instead of Kirki.
  
### Fix for kirki-simple-color
- Add this to the `enqueue` method: `wp_enqueue_style( 'wp-color-picker' );` 
- For `bizberg-simple-color-js` enqueue, also add `wp-color-picker` as the dependency along with the `jQuery`.

### Fix for kirki-advanced-repeater
- Add this to the `enqueue` method:
  ```
	wp_enqueue_script( 'select2', 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js', array( 'jquery' ), '0.1', true );
	wp_enqueue_style( 
		'select2', 
		'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css' 
	);
- For `bizberg-kirki-advanced-repeater-js` enqueue, also add `select2` as the dependency along with the existing dependencies.

**Comment by ravishakya** [comment]
Hi,

Currently, I haven't tested the new version with the theme. Once it is stable enough the custom controls need some makeup. Thank you for the extra codes.

**Comment by contactjavas** [comment]
Hi @ravishakya , finally a fix for that bug :) . The problem was the `active_callback` on CSS output didn't respect the default value.
I've tested this `v4.0.10` and it fixes the bug.
Download link [v4.0.10](https://github.com/kirki-framework/kirki/files/7839148/kirki.zip)

Thanks!

**Comment by ravishakya** [comment]
Finally, it is working for me. I can see the changes in the customizer and frontend. I will test more and if any issues are found will tell you guys. Thank you for the great work.
