### ISSUE TITLE
Description does not render HTML

### ISSUE THREAD

**Issue by ravishakya** [presscodes/kirki#2439]
Previously, you can use HTML tags in descriptions. Now everything is escaped.

**New**
![image](https://user-images.githubusercontent.com/11089018/149449196-0096912b-7608-4ba0-80ff-45e1a64d3561.png)

**Old Version**
![image](https://user-images.githubusercontent.com/11089018/149449400-119b0125-ff42-463c-9606-34739bc70b35.png)

**Comment by contactjavas** [comment]
Hi @ravishakya , thanks for reporting the issue :)

I can confirm it, where some controls didn't allow HTML in the description.
This has been fixed in `v4.0.14`. Download link: [v4.0.14](https://github.com/kirki-framework/kirki/files/7871806/kirki.zip)

Please let us know if this fixes the issue on your side.
Thanks :)

**Comment by ravishakya** [comment]
The issue has been fixed.

Thank You
