### ISSUE TITLE
Transport auto doesn't run value through sanitize_callback

### ISSUE THREAD

**Issue by JiveDig** [presscodes/kirki#2453]
Using 4.0.20

I have a text field where users can put in a number or a CSS value like 30px, 2rem, 2em, etc. If an integer is added, my sanitize_callback adds px at the end. Using transport => auto just uses the integer value in the CSS. This may be a product of how transport auto works in JS only, but I wanted to confirm.

**Comment by contactjavas** [comment]
Hi @JiveDig , thanks for confirming this.

From what I understand, the `postMessage` CSS output will output the value based on:
- how the control handle the value and then displaying it to the markup via `content_template` method in PHP or via JS part of the control.
- what the control prints into the JS object (via `to_json()` method in PHP)
- how the JS part of the control handles that object
- and how the JS part of the control handles the value returned from the customizer

In your use-case, let's say you enter `11` to the text input. Your custom `sanitize_callback` will add `px` to it before it's saved to the database. But the control still seeing the value as `11` instead of `11px`. In this case, you would need a custom JS to handle this in order to make the CSS output generated by `postMessage` works as expected. You might already know, the filter name is `kirkiPostMessageStylesOutput`.

You might also already have the script for that. So, this is just an example to do that:

```js
(function () {
  /**
   * Check if the provided value is a numeric.
   *
   * @see https://stackoverflow.com/questions/175739/built-in-way-in-javascript-to-check-if-a-string-is-a-valid-number#answer-175787
   *
   * @param {string|number} str The provided value.
   * @return bool
   */
  function isNumeric(str) {
    // Number is a numeric.
    if ("number" === typeof str) return true;

    // We only process strings.
    if ("string" !== typeof str) return false;

    // Use type coercion to parse the entirety of the string (`parseFloat` alone does not do this) and ensure strings of whitespace fail.
    return !isNaN(str) && !isNaN(parseFloat(str));
  }

  /**
   * Function to hook into `kirkiPostMessageStylesOutput` filter.
   *
   * @param {string} styles The styles to be filtered.
   * @param {mixed} value The control's value.
   * @param {Object} output The control's output argument.
   * @param {string} controlType The control type.
   *
   * @return {string} The filtered styles.
   */
  function stylesOutput(styles, value, output, controlType) {
    // These checks are just example :).
    if ("kirki-generic" !== controlType) return styles;
    if (!isNumeric(value)) return styles;

    styles +=
      output.element +
      "{" +
      output.property +
      ": " +
      value + "px" +
      ";\
		}";

    return styles;
  }

  // Hook the function to the `kirkiPostMessageStylesOutput` filter.
  wp.hooks.addFilter("kirkiPostMessageStylesOutput", "kirki", stylesOutput);
})();
```

We also do custom JS in some controls such as in `control-react-colorful`, `field-typography`, and `field-dimensions` to make the CSS output of `postMessage` output the styles in the expected format. There, people can check where to enqueue, and what are the dependencies.

**Comment by JiveDig** [comment]
Okay cool, thanks. This explanation may be beneficial in the docs, maybe around the transport stuff.
